export const ADD_ITEM = 'ADD_ITEM'
export const DEL_ITEM = 'DEL_ITEM'
export const ADD_IMG = 'ADD_IMG'
export const DEL_IMG = 'DEL_IMG'
export const EDIT_ITEM = 'EDIT_ITEM'
export const EDIT_TEXT = 'EDIT_TEXT'
export const LOADING_IMG = 'LOADING_IMG'
